### ISSUE TITLE
streamtape.com and streamsb.com support

### ISSUE THREAD

**Issue by andta200** [wywxz/SimpleUploaderBot#1]
Hi,

fembed download ✅ upload ❌
streamtape.com and streamsb.com support, please!..

Thanks...

**Comment by serranx** [comment]
✅ Fembed working
✅ Added streamtape
❌ Streamsb 😢

https://t.me/SimpleUploaderBot

**Comment by N-SUDY** [comment]
Some mediafire link not working

**Comment by serranx** [comment]
> Some mediafire link not working

Send link

**Comment by andta200** [comment]
wrong people 😌

26 Eki 2022 Çar 23:48 tarihinde wywxz ***@***.***> şunu yazdı:

**Comment by N-SUDY** [comment]
> > Some mediafire link not working
> 
> Send link

https://www.mediafire.com/file/nw1hwtqkgunxcti/%255BAnime_Myanmar_Cafe%255D_One_Piece_Episode_0011_MM_SUB_%255B1440_x_1080%255D_%255BHEVC%255D.mp4/file


This type of link are not working
![Screenshot_20221027_052934](https://user-images.githubusercontent.com/115041575/198154457-ec43d20e-78db-4dc5-bfbd-bf6571dc0307.jpg)

**Comment by serranx** [comment]
> > > Some mediafire link not working
> > 
> > 
> > Send link
> 
> https://www.mediafire.com/file/nw1hwtqkgunxcti/%255BAnime_Myanmar_Cafe%255D_One_Piece_Episode_0011_MM_SUB_%255B1440_x_1080%255D_%255BHEVC%255D.mp4/file
> 
> This type of link are not working ![Screenshot_20221027_052934](https://user-images.githubusercontent.com/115041575/198154457-ec43d20e-78db-4dc5-bfbd-bf6571dc0307.jpg)

Try now

**Comment by N-SUDY** [comment]
> > > > Some mediafire link not working
> > > 
> > > 
> > > Send link
> > 
> > 
> > https://www.mediafire.com/file/nw1hwtqkgunxcti/%255BAnime_Myanmar_Cafe%255D_One_Piece_Episode_0011_MM_SUB_%255B1440_x_1080%255D_%255BHEVC%255D.mp4/file
> > This type of link are not working ![Screenshot_20221027_052934](https://user-images.githubusercontent.com/115041575/198154457-ec43d20e-78db-4dc5-bfbd-bf6571dc0307.jpg)
> 
> Try now

Thank A lot bro
I really appreciate. 
I was deploy in vps later,now working perfectly with heroku.
